apiVersion: apps/v1
kind: Deployment
metadata:
  name: super-weather-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: super-weather-backend
  template:
    metadata:
      labels:
        app: super-weather-backend
    spec:
      containers:
        - name: backend-golang-container
          image: ajj132/super-weather-app-bff:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "128m"
            limits:
              memory: "128Mi"
              cpu: "256m"
          ports:
            - containerPort: 8082
