apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-database
  template:
    metadata:
      labels:
        app: login-database
    spec:
      containers:
        - name: login-postgres-container
          image: ajj132/super-weather-app-login-database:latest
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: login_db
          ports:
            - containerPort: 5432
