version: '3'
services:
  dbmanager:
    build: ./dbmanager
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
  mongodb:
    image: mongo:latest
    volumes:
      - ./mongodb/data:/data/db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
