name: Super Weather App CI/CD

on:
  push:
    branches:
      - main

env:
  BUILD_ID: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build BFF
      run: |
        cd Backend-For-Frontend
        docker buildx build --push -t ajj132/super-weather-app-bff:${{ env.BUILD_ID }} .

    - name: Build Cache Database Manager
      run: |
        cd cache-database/dbmanager
        docker buildx build --push -t ajj132/super-weather-app-cache:${{ env.BUILD_ID }} .

    - name: Build Cache MongoDB
      run: |
        cd cache-database/mongodb
        docker buildx build --push -t ajj132/super-weather-app-cache-database:${{ env.BUILD_ID }} .

    - name: Build Front-end
      run: |
        cd front-end/superfluous-weather-app
        npm run build
        docker buildx build --push -t ajj132/super-weather-app-frontend:${{ env.BUILD_ID }} .

    - name: Build User Manager
      run: |
        cd login-system/user-manager
        docker buildx build --push -t ajj132/super-weather-app-login:${{ env.BUILD_ID }} .

    - name: Build User Database
      run: |
        cd login-system/user-database
        docker buildx build --push -t ajj132/super-weather-app-login-database:${{ env.BUILD_ID }} .

    - name: Build Weather Manager
      run: |
        cd weather-manager
        docker buildx build --push -t ajj132/super-weather-app-weather-mngr:${{ env.BUILD_ID }} .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Local Deploy
      run: |
        cd k8s
        minikube start
        kubectl delete -f .
        kubectl apply -f .

  load-test:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build Load Tester
      run: |
        cd Load-Test
        docker buildx build --push -t ajj132/super-weather-app-load-tester:${{ env.BUILD_ID }} .

    - name: Load Testing
      run: |
        cd Load-Test
        ./load-test.jmx

    - name: Analyze Results
      run: |
        # Perform your analysis here (example: using Performance plugin)
